---

version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2 # https://circleci.com/developer/orbs/orb/circleci/ruby
  node: circleci/node@4.2.1 # https://circleci.com/developer/orbs/orb/circleci/node

# executors description
executors:
  docker_node:
    docker:
      - image: "circleci/node:lts"
    resource_class: small
    working_directory: ~/demo-react-native
    environment:
      JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

jobs:
  unit_tests:
    executor: docker_node
    parallelism: 4

    steps:
      ### manage deps
      - checkout
      - node/install-packages:
          # not standart cmd example
          override-ci-command: >-
            yarn
            --no-progress
            --frozen-lockfile
            --cache-folder /tmp/cache/yarn
          pkg-manager: 'yarn' # not standart package manager example
      - persist_to_workspace: # example how to pass dir to another step even in another container
          root: ~/demo-react-native
          paths:
            - node_modules

      ### tests
      - run:
          name: run unit-tests
          command: |
            mkdir -p test-results/jest
            TEST=$(circleci tests glob **/__tests__/*.js | circleci tests split --split-by=timings)
            yarn test $TEST

      ### job artifacts
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  node-android:
    jobs:
      - unit_tests

...
